spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:territory}
    username: ${DB_USERNAME:minjae389}
    password: ${DB_PASSWORD:1619}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # ❌ dialect 지정하지 마!
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
