spring:
  jwt:
    secret: ${JWT_SECRET}
  datasource:
    url: jdbc:postgresql://localhost:5432/territory
    username: minjae389    # 로컬 DB 계정
    password: 1619         # 비밀번호
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true